name: base
channels:
  - defaults
dependencies:
  - _anaconda_depends=2020.07=py38_0
  - _ipyw_jlab_nb_ext_conf=0.1.0=py38_0
  - alabaster=0.7.12=pyhd3eb1b0_0
  - anaconda=custom=py38_4
  - anaconda-client=1.7.2=py38_0
  - anaconda-navigator=2.0.3=py38_0
  - anaconda-project=0.11.1=py38hecd8cb5_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - applaunchservices=0.2.1=pyhd3eb1b0_0
  - appnope=0.1.2=py38hecd8cb5_1001
  - appscript=1.1.2=py38h9ed2024_0
  - argh=0.29.4=py38hecd8cb5_0
  - argon2-cffi=20.1.0=py38h9ed2024_1
  - asn1crypto=1.5.1=py38hecd8cb5_0
  - astroid=2.5=py38hecd8cb5_1
  - astropy=4.2.1=py38h9ed2024_1
  - atomicwrites=1.4.0=py_0
  - autopep8=1.5.6=pyhd3eb1b0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - backports=1.1=pyhd3eb1b0_1
  - backports.functools_lru_cache=1.6.4=pyhd3eb1b0_0
  - backports.shutil_get_terminal_size=1.0.0=pyhd3eb1b0_3
  - backports.tempfile=1.0=pyhd3eb1b0_1
  - backports.weakref=1.0.post1=py_1
  - beautifulsoup4=4.12.3=py38hecd8cb5_0
  - bitarray=2.5.1=py38hca72f7f_0
  - bkcharts=0.2=py38hecd8cb5_1
  - black=19.10b0=py_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.3=hcec6c5f_0
  - boto=2.49.0=py38_0
  - bottleneck=1.3.2=py38hf1fa96c_1
  - brotli-python=1.0.9=py38hcec6c5f_8
  - brotlipy=0.7.0=py38h9ed2024_1003
  - bzip2=1.0.8=h6c40b1e_6
  - c-ares=1.19.1=h6c40b1e_0
  - ca-certificates=2025.2.25=hecd8cb5_0
  - cctools=949.0.1=h9abeeb2_25
  - cctools_osx-64=949.0.1=hc7db93f_25
  - certifi=2024.8.30=py38hecd8cb5_0
  - cffi=1.14.5=py38h2125817_0
  - chardet=4.0.0=py38hecd8cb5_1003
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cloudpickle=3.0.0=py38hecd8cb5_0
  - clyent=1.2.2=py38_1
  - colorama=0.4.6=py38hecd8cb5_0
  - conda=22.9.0=py38hecd8cb5_0
  - conda-build=3.24.0=py38hecd8cb5_0
  - conda-content-trust=0.1.3=py38hecd8cb5_0
  - conda-env=2.6.0=1
  - conda-pack=0.7.1=py38hecd8cb5_0
  - conda-package-handling=1.9.0=py38hca72f7f_1
  - conda-repo-cli=1.0.4=pyhd3eb1b0_0
  - conda-token=0.4.0=pyhd3eb1b0_0
  - conda-verify=3.4.2=py_1
  - contextlib2=21.6.0=py38hecd8cb5_0
  - cryptography=3.4.7=py38h2fd3fbb_0
  - curl=7.71.1=hb0a8c7a_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - cython=3.0.11=py38h46256e1_0
  - cytoolz=0.11.0=py38haf1e3a3_0
  - dask=2022.2.1=pyhd3eb1b0_0
  - dask-core=2022.2.1=pyhd3eb1b0_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - dbus=1.13.18=h18a8e69_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - distributed=2022.2.1=pyhd3eb1b0_0
  - docutils=0.17=py38hecd8cb5_1
  - entrypoints=0.4=py38hecd8cb5_0
  - et_xmlfile=1.1.0=py38hecd8cb5_0
  - exceptiongroup=1.2.0=py38hecd8cb5_0
  - expat=2.7.1=h6d0c2b6_0
  - fastcache=1.1.0=py38h1de35cc_0
  - filelock=3.6.0=pyhd3eb1b0_0
  - flake8=3.9.0=pyhd3eb1b0_0
  - flask=1.1.2=pyhd3eb1b0_0
  - freetype=2.13.3=h02243ff_0
  - future=0.18.3=py38hecd8cb5_0
  - get_terminal_size=1.0.0=h7520d66_0
  - gettext=0.21.0=h7535e17_0
  - gevent=21.1.2=py38h9ed2024_1
  - glib=2.68.1=hdf23fa2_0
  - glob2=0.7=pyhd3eb1b0_0
  - gmp=6.3.0=h6d0c2b6_0
  - gmpy2=2.0.8=py38h6ef4df4_3
  - greenlet=1.0.0=py38h23ab428_2
  - h5py=2.10.0=py38h3134771_0
  - hdf5=1.10.4=hfa1e0ec_0
  - heapdict=1.0.1=pyhd3eb1b0_0
  - html5lib=1.1=pyhd3eb1b0_0
  - icu=58.2=h0a44026_3
  - idna=3.7=py38hecd8cb5_0
  - imageio=2.9.0=pyhd3eb1b0_0
  - imagesize=1.4.1=py38hecd8cb5_0
  - importlib-metadata=4.11.3=py38hecd8cb5_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2021.2.0=hecd8cb5_564
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_2
  - isort=5.9.3=pyhd3eb1b0_0
  - itsdangerous=2.2.0=py38hecd8cb5_0
  - jbig=2.1=h4d881f8_0
  - jdcal=1.4.1=pyhd3eb1b0_0
  - jedi=0.17.2=py38hecd8cb5_1
  - jinja2=2.11.3=pyhd3eb1b0_0
  - joblib=1.4.2=py38hecd8cb5_0
  - jpeg=9e=h46256e1_3
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter=1.0.0=py38_7
  - jupyter_client=7.1.2=pyhd3eb1b0_0
  - jupyter_console=6.4.3=pyhd3eb1b0_0
  - jupyter_core=5.7.2=py38hecd8cb5_0
  - jupyter_server=1.4.1=py38hecd8cb5_0
  - jupyterlab=3.3.2=pyhd3eb1b0_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.10.3=pyhd3eb1b0_1
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - keyring=22.3.0=py38hecd8cb5_0
  - kiwisolver=1.4.4=py38hcec6c5f_0
  - krb5=1.18.2=h75d18d8_0
  - lazy-object-proxy=1.10.0=py38h6c40b1e_0
  - lcms2=2.16=h31d93a5_1
  - ld64=530=h20443b4_25
  - ld64_osx-64=530=h70f3046_25
  - ldid=2.1.5=hc58f1be_3
  - lerc=4.0.0=h6d0c2b6_0
  - libarchive=3.6.2=h65c5294_0
  - libcurl=7.71.1=h8a08a2b_1
  - libcxx=14.0.6=h9765a3e_0
  - libdeflate=1.22=h46256e1_0
  - libedit=3.1.20230828=h6c40b1e_0
  - libev=4.33=h9ed2024_1
  - libffi=3.3=hb1e8313_2
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.16=h6c40b1e_3
  - liblief=0.10.1=h0a44026_0
  - libllvm10=10.0.1=h76017ad_5
  - libllvm14=14.0.6=he552d86_0
  - libllvm9=9.0.1=h21ff451_1
  - libpng=1.6.39=h6c40b1e_0
  - libsodium=1.0.18=h1de35cc_0
  - libspatialindex=1.9.3=h23ab428_0
  - libssh2=1.9.0=ha12b0ac_1
  - libtiff=4.7.0=h2dfa3ea_0
  - libuv=1.48.0=h46256e1_0
  - libwebp-base=1.3.2=h46256e1_1
  - libxml2=2.9.14=hbf8cd5e_0
  - libxslt=1.1.34=h83b36ba_0
  - llvm-openmp=14.0.6=h0dcd299_0
  - llvmlite=0.36.0=py38he4411ff_4
  - locket=1.0.0=py38hecd8cb5_0
  - lxml=4.6.3=py38h26b266a_0
  - lz4-c=1.9.4=hcec6c5f_1
  - lzo=2.10=haf1e3a3_2
  - markupsafe=1.1.1=py38h1de35cc_1
  - mccabe=0.6.1=py38hecd8cb5_2
  - mistune=0.8.4=py38h1de35cc_1001
  - mkl=2021.4.0=hecd8cb5_637
  - mkl-service=2.4.0=py38h9ed2024_0
  - mkl_fft=1.3.0=py38h4a7008c_2
  - mkl_random=1.2.1=py38hb2f4e1b_2
  - mock=4.0.3=pyhd3eb1b0_0
  - more-itertools=10.3.0=py38hecd8cb5_0
  - mpc=1.3.1=h46256e1_0
  - mpfr=4.2.1=h46256e1_0
  - mpmath=1.3.0=py38hecd8cb5_0
  - msgpack-python=1.0.3=py38haf03e11_0
  - multipledispatch=0.6.0=py38_0
  - mypy_extensions=1.0.0=py38hecd8cb5_0
  - navigator-updater=0.2.1=py38_0
  - nbclassic=0.2.6=pyhd3eb1b0_0
  - nbclient=0.5.11=pyhd3eb1b0_0
  - nbconvert=6.0.7=py38_0
  - nbformat=5.10.4=py38hecd8cb5_0
  - ncurses=6.4=hcec6c5f_0
  - nest-asyncio=1.6.0=py38hecd8cb5_0
  - networkx=2.7.1=pyhd3eb1b0_0
  - nltk=3.6.1=pyhd3eb1b0_0
  - nose=1.3.7=pyhd3eb1b0_1008
  - notebook=6.3.0=py38hecd8cb5_0
  - numba=0.53.1=py38hb2f4e1b_0
  - numexpr=2.7.3=py38h5873af2_1
  - numpydoc=1.2=pyhd3eb1b0_0
  - olefile=0.46=pyhd3eb1b0_0
  - openpyxl=3.1.5=py38h46256e1_0
  - openssl=1.1.1w=hca72f7f_0
  - packaging=23.2=py38hecd8cb5_0
  - pandas=1.2.4=py38h23ab428_0
  - pandoc=2.12=hecd8cb5_3
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.7.0=py_0
  - partd=1.2.0=pyhd3eb1b0_1
  - patch=2.7.6=h1de35cc_1001
  - path=16.2.0=pyhd3eb1b0_0
  - path.py=12.5.0=hd3eb1b0_0
  - pathlib2=2.3.6=py38hecd8cb5_2
  - pathspec=0.10.3=py38hecd8cb5_0
  - pathtools=0.1.2=pyhd3eb1b0_1
  - patsy=0.5.1=py38_0
  - pcre=8.45=h23ab428_0
  - pep8=1.7.1=py38hecd8cb5_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.2.0=py38h5270095_0
  - pkginfo=1.8.2=pyhd3eb1b0_0
  - platformdirs=2.5.2=py38hecd8cb5_0
  - pluggy=0.13.1=py38hecd8cb5_0
  - ply=3.11=py38_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.43=py38hecd8cb5_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py38hca72f7f_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - py=1.11.0=pyhd3eb1b0_0
  - py-lief=0.10.1=py38haf313ee_0
  - pycodestyle=2.6.0=pyhd3eb1b0_0
  - pycosat=0.6.6=py38h6c40b1e_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pycurl=7.43.0.6=py38hddc9c9b_0
  - pydocstyle=6.3.0=py38hecd8cb5_0
  - pyerfa=1.7.3=py38h9ed2024_0
  - pyflakes=2.2.0=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pylint=2.7.4=py38hecd8cb5_1
  - pyls-black=0.4.6=hd3eb1b0_0
  - pyls-spyder=0.3.2=pyhd3eb1b0_0
  - pyodbc=4.0.30=py38h0a44026_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h655552a_2
  - pyrsistent=0.20.0=py38h6c40b1e_0
  - pysocks=1.7.1=py38_1
  - pytables=3.6.1=py38h4727e94_0
  - pytest=7.4.4=py38hecd8cb5_0
  - python=3.8.8=h88f2d9e_5
  - python-dateutil=2.9.0post0=py38hecd8cb5_2
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - python-jsonrpc-server=0.4.0=py_0
  - python-language-server=0.36.2=pyhd3eb1b0_0
  - python-libarchive-c=5.1=pyhd3eb1b0_0
  - python.app=3=py38h9ed2024_0
  - pytz=2024.1=py38hecd8cb5_0
  - pywavelets=1.1.1=py38haf1e3a3_2
  - pyyaml=6.0.2=py38h46256e1_0
  - pyzmq=20.0.0=py38h23ab428_1
  - qdarkstyle=2.8.1=py_0
  - qt=5.9.7=h468cd18_1
  - qtawesome=1.0.3=pyhd3eb1b0_0
  - qtconsole=5.3.0=pyhd3eb1b0_0
  - qtpy=2.4.1=py38hecd8cb5_0
  - readline=8.2=hca72f7f_0
  - regex=2021.4.4=py38h9ed2024_0
  - requests=2.32.3=py38hecd8cb5_0
  - ripgrep=14.1.0=hb9d2255_0
  - rope=0.22.0=pyhd3eb1b0_0
  - rtree=1.0.1=py38hecd8cb5_0
  - ruamel_yaml=0.15.100=py38h9ed2024_0
  - scikit-image=0.18.1=py38hb2f4e1b_0
  - scikit-learn=1.1.3=py38hcec6c5f_1
  - seaborn=0.12.2=py38hecd8cb5_0
  - send2trash=1.8.2=py38hecd8cb5_0
  - setuptools=72.1.0=py38hecd8cb5_0
  - simplegeneric=0.8.1=py38_2
  - singledispatch=3.7.0=pyhd3eb1b0_1001
  - sip=4.19.8=py38h0a44026_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=h6d0c2b6_0
  - sniffio=1.3.0=py38hecd8cb5_0
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcollections=2.1.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.5=py38hecd8cb5_0
  - sphinx=4.0.1=pyhd3eb1b0_0
  - sphinxcontrib=1.0=py38_1
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.4=pyhd3eb1b0_0
  - sphinxcontrib-websupport=1.2.4=py_0
  - spyder=4.2.5=py38hecd8cb5_0
  - spyder-kernels=1.10.2=py38hecd8cb5_0
  - sqlalchemy=1.4.51=py38h6c40b1e_0
  - sqlite=3.45.3=h6c40b1e_0
  - statsmodels=0.12.2=py38h9ed2024_0
  - sympy=1.13.3=py38hecd8cb5_0
  - tapi=1000.10.8=ha1b3eb9_0
  - tbb=2020.3=h879752b_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - terminado=0.17.1=py38hecd8cb5_0
  - testpath=0.6.0=py38hecd8cb5_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tifffile=2020.10.1=py38h0cf3a3e_2
  - tk=8.6.14=h0a12a5f_1
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py38hecd8cb5_0
  - toolz=0.12.0=py38hecd8cb5_0
  - tornado=6.1=py38h9ed2024_0
  - typed-ast=1.5.5=py38h6c40b1e_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - ujson=5.10.0=py38h6d0c2b6_0
  - unicodecsv=0.14.1=py38_0
  - unixodbc=2.3.11=hb456775_0
  - urllib3=1.26.19=py38hecd8cb5_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - werkzeug=2.0.3=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py38_0
  - wrapt=1.12.1=py38haf1e3a3_1
  - wurlitzer=3.0.2=py38hecd8cb5_0
  - xlrd=2.0.1=pyhd3eb1b0_1
  - xlsxwriter=3.0.3=pyhd3eb1b0_0
  - xlwings=0.23.0=py38hecd8cb5_0
  - xlwt=1.3.0=py38_0
  - xmltodict=0.12.0=pyhd3eb1b0_0
  - xz=5.6.4=h46256e1_1
  - yaml=0.2.5=haf1e3a3_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - zeromq=4.3.5=hcec6c5f_0
  - zict=2.0.0=pyhd3eb1b0_0
  - zipp=3.20.2=py38hecd8cb5_0
  - zlib=1.2.13=h4b97444_1
  - zope=1.0=py38_1
  - zope.event=5.0=py38hecd8cb5_0
  - zope.interface=5.3.0=py38h9ed2024_0
  - zstd=1.5.6=h138b38a_0
  - pip:
    - absl-py==2.1.0
    - accelerate==0.26.1
    - aiohttp==3.9.3
    - aiosignal==1.3.1
    - anyio==4.2.0
    - asciitree==0.3.3
    - asgiref==3.4.1
    - asttokens==2.1.0
    - astunparse==1.6.3
    - async-timeout==4.0.3
    - attrs==19.3.0
    - autograd==1.6.2
    - backports-zoneinfo==0.2.1
    - bayesian-changepoint-detection==0.2.dev1
    - bidsschematools==0.7.1
    - bitsandbytes==0.42.0
    - blessed==1.20.0
    - bokeh==2.4.3
    - boto3==1.27.1
    - botocore==1.30.1
    - cachetools==4.2.4
    - cattrs==1.0.0rc0
    - chspy==1.2.2
    - ci-info==0.3.0
    - click==8.1.3
    - click-didyoumean==0.3.0
    - colorcet==3.0.0
    - commonmark==0.9.1
    - contourpy==1.1.0
    - dandi==0.55.1
    - dandischema==0.8.4
    - datajoint==0.14.0
    - datasets==2.16.1
    - debugpy==1.6.3
    - dill==0.3.7
    - distro==1.9.0
    - dnspython==2.3.0
    - efficientnet==1.0.0
    - email-validator==2.0.0.post2
    - etelemetry==0.3.0
    - executing==1.2.0
    - factor-analyzer==0.5.1
    - fasteners==0.18
    - ffmpeg==1.4
    - ffmpeg-python==0.2.0
    - flatbuffers==23.5.26
    - fonttools==4.42.1
    - frozenlist==1.4.1
    - fscacher==0.3.0
    - fsspec==2023.10.0
    - gast==0.3.3
    - geotorch==0.3.0
    - ghp-import==2.0.2
    - google-auth==2.27.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.60.1
    - h11==0.14.0
    - hdmf==3.6.1
    - holoviews==1.15.2
    - httpcore==1.0.2
    - httpx==0.26.0
    - huggingface-hub==0.20.3
    - humanize==4.7.0
    - image-classifiers==1.0.0
    - imgaug==0.3.0
    - imgstore==0.2.9
    - importlib-resources==5.12.0
    - interleave==0.2.1
    - ipykernel==6.17.1
    - ipympl==0.9.3
    - ipython==8.6.0
    - isodate==0.6.1
    - jaraco-classes==3.2.3
    - jitcdde==1.8.1
    - jitcxde-common==1.5.4
    - jmespath==1.0.1
    - jpca==0.0.1
    - jsmin==3.0.0
    - jsonpickle==1.2
    - jsonpointer==2.4
    - jupyterthemes==0.20.0
    - kaleido==0.2.1
    - keras==2.11.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - keyrings-alt==4.2.0
    - lesscpy==0.15.1
    - libclang==16.0.6
    - markdown==3.3.4
    - matplotlib==3.7.2
    - matplotlib-inline==0.1.6
    - mergedeep==1.3.4
    - minio==7.1.14
    - mkdocs==1.3.0
    - mtscomp==1.0.2
    - multidict==6.0.5
    - multiprocess==0.70.15
    - natsort==8.4.0
    - neural-decoding==0.1.5
    - neuron==8.0.2
    - nimfa==1.4.0
    - nlb-tools==0.0.3
    - np-utils==0.6.0
    - numcodecs==0.11.0
    - numpy==1.22.0
    - nwbinspector==0.4.29
    - oauthlib==3.1.1
    - openai==1.7.2
    - opencv-python-headless==4.2.0.34
    - opt-einsum==3.3.0
    - otumat==0.3.1
    - panel==0.14.1
    - param==1.12.1
    - peft==0.8.2
    - phy==2.0b5
    - phylib==2.4.1
    - pip==24.0
    - plotly==5.11.0
    - protobuf==3.19.6
    - pure-eval==0.2.2
    - pyarrow==15.0.0
    - pyarrow-hotfix==0.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycryptodomex==3.18.0
    - pyct==0.4.8
    - pydantic==1.10.11
    - pydot==1.4.2
    - pyglmnet==1.1
    - pykalman==0.9.5
    - pymysql==1.0.3
    - pynndescent==0.5.5
    - pynwb==2.3.3
    - pyopengl==3.1.6
    - pyout==0.7.3
    - pyqt5==5.15.6
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.10.1
    - pyqtwebengine==5.15.5
    - pyqtwebengine-qt5==5.15.2
    - pyside2==5.14.1
    - python-rapidjson==1.5
    - pytz-deprecation-shim==0.1.0.post0
    - pyviz-comms==2.2.1
    - pyyaml-env-tag==0.1
    - qimage2ndarray==1.8
    - requests-oauthlib==1.3.0
    - rfc3987==1.3.8
    - rich==9.10.0
    - rsa==4.7.2
    - ruamel-yaml==0.17.32
    - ruamel-yaml-clib==0.2.7
    - s3transfer==0.6.1
    - safetensors==0.4.2
    - scikit-video==1.1.11
    - scipy==1.4.1
    - segmentation-models==1.0.1
    - semantic-version==2.10.0
    - shapely==1.7.1
    - shiboken2==5.14.1
    - sklearn==0.0
    - sleap==1.1.5
    - sqlparse==0.4.2
    - stack-data==0.6.0
    - strict-rfc3339==0.7
    - svgwrite==1.4.1
    - symengine==0.11.0
    - tenacity==8.1.0
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.11.0
    - tensorflow-estimator==2.11.0
    - tensorflow-io-gcs-filesystem==0.34.0
    - termcolor==1.1.0
    - tokenizers==0.15.1
    - torch==1.13.1
    - torchvision==0.14.1
    - tqdm==4.65.0
    - traitlets==5.5.0
    - transformers==4.37.2
    - tree==0.2.4
    - typing-extensions==4.5.0
    - tzdata==2021.2.post0
    - tzlocal==4.0
    - umap-learn==0.5.2
    - watchdog==2.1.7
    - webcolors==1.13
    - xxhash==3.4.1
    - yarl==1.9.4
    - zarr==2.15.0
    - zarr-checksum==0.2.9
prefix: /Users/sherryan/anaconda3
